language: node_js
node_js:
- stable
- '7'
- '6'
- '5'
script:
- npm run bootstrap
- npm test
before_deploy: cd packages/visual-stack-docs && npm run build
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAIJJOI6I63H2JRUSA
  secret_access_key:
    secure: D6kKxoZ371Czc843l/8VDQR5lkVA1Q7LD9pU5AkCpp4Ih2YPV+p0dg97CgHoMEdzZxHg6pKjyHy9T2g0RwolwPmWF+niLe5Upgo7LJeENb2jEUvnSJK7G4DXsoqRceTzJPjfF446Flj5hPlPjLpRhWoUVlbQZpudZeenUTmAmTT7AKPYUN4UmCgt1V9Nxjl4q762fhVdz+Wg2AzilgXRhu/GUSLuMieay+Bf2eV7kHvUnQ8cqwBAWRk0GNzyFKw2obi1qZWN6UxxJt0RF2kDl9+Rh8kVBM38utRaN2twZSvXEZGi3gbGe5ASTVyEOyzZbDEtB+7Oyo0Twr3dUUUuaG3j+lEwJGxqdGDVhHgtlKcvDjLqxRVZzv5++mcLJVmlL5KPUDeEvdhzuqa10LWTjr4AHEjnvs3wtFNP4R5MRq6Its7haYhOxG1DPAjGFQf3adWC2QOApM4tT7+fyo30sYflWJn91CSTCY+4w75phJRVmLbb/11x25Fgp5o9kLD+y835G3+miWvIR0XCx7xpmcSH9/Tn696xg0AbpG7UslX7qrIZCuk7hIj5Ja8bUHplxN9ZgVv+UV2ODhCO7q+RUYG2pb/nWdiBaBQuXGeeZMlwAdv7MC89PEMVNO1B9ZMb38Z8fplR1zF592pnmOPnTs1DV0vy01foSpf3xADL+p8=
  bucket: visual-stack-dev
  local-dir: build
  acl: public_read
  on:
    repo: cjdev/visual-stack
    node: stable
    branch: master
