language: node_js
node_js:
  - 4.0.0
  - 4.1.2
  - 4.2.6
  - 4.3.2
  - 5.0.0
  - 5.1.1
  - 5.2.0
  - 5.3.0
  - 5.4.1
  - 5.5.0
  - 5.6.0
  - 5.7.1
  - stable

script:
  - npm run bootstrap
  - npm test
